<?php

namespace AppBundle\Repository;

/**
 * PersoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoneRepository extends \Doctrine\ORM\EntityRepository
{
}
